#!/usr/bin/env bash

set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

############################################################################
# Bevy Farm Game Helper Scripts
############################################################################

# start local network with old test-ledger data
function start() {}

# start local network with cleaned data
function start-new() {}

eval "$@"
